// Order of keys will be order displayed and order of categories will be displayed in alphabetical order
interface categorySectionObject {
  [categorySection: string]: string[];
}

const categoryStructure: categorySectionObject = {
  buildings: [
    "barber-surgeon",
    "blacksmith",
    "bone-smith",
    "catarium",
    "dragon-armory",
    "exhausted-lantern-hoard",
    "gormchymist",
    "gormery",
    "leather-worker",
    "light-forging",
    "mask-maker",
    "organ-grinder",
    "plumery",
    "rare-gear",
    "sacred-pool",
    "sense-memory",
    "silk-mill",
    "skinnery",
    "skyreef-sanctuary",
    "starting-gear",
    "stone-circle",
    "weapon-crafter",
    "wet-resin-crafter",
  ],
  affinities: ["blue", "green", "red"],
  primaryCategories: ["armor", "item", "weapon"],
  weaponTypes: [
    "axe",
    "bow",
    "club",
    "dagger",
    "grand-weapon",
    "katana",
    "katar",
    "scythe",
    "shield",
    "spear",
    "sword",
    "whip",
  ],
  armorSets: [
    "white-lion-armor",
    "screaming-armor",
    "phoenix-armor",
    "rawhide-armor",
    "leather-armor",
    "lantern-armor",
    "dragon-armor",
    "silk-armor",
    "cycloid-scale-armor",
    "dancer-armor",
    "rolling-armor",
    "warlord-armor",
    "green-armor",
  ],
  armorLocations: ["arm-armor", "body-armor", "head-armor", "leg-armor", "waist-armor"],
  miscellaneous: [
    "amber",
    "ammunition",
    "arrow",
    "badge",
    "balm",
    "bone",
    "consumable",
    "feather",
    "finesse",
    "flammable",
    "fragile",
    "fur",
    "gloomy",
    "gormskin",
    "heavy",
    "herb",
    "hook",
    "instrument",
    "jewelery",
    "knight",
    "lantern",
    "leather",
    "mask",
    "melee",
    "metal",
    "mineral",
    "noisy",
    "other",
    "paired",
    "pickaxe",
    "ranged",
    "rawhide",
    "scale",
    "scimitar",
    "set",
    "sickle",
    "soluble",
    "stinky",
    "stone",
    "symbol",
    "thrown",
    "tool",
    "two-handed",
  ],
};

export default categoryStructure;
