// Order of keys will be order displayed and order of categories will be displayed in alphabetical order
interface categorySectionObject {
  [categorySection: string]: string[];
}

const categoryStructure: categorySectionObject = {
  buildings: [
    "barber-surgeon",
    "blacksmith",
    "bone-smith",
    "catarium",
    "exhausted-lantern-hoard",
    "leather-worker",
    "mask-maker",
    "organ-grinder",
    "plumery",
    "rare-gear",
    "skinnery",
    "starting-gear",
    "stone-circle",
    "weapon-crafter",
  ],
  affinities: ["blue", "green", "red"],
  primaryCategories: ["armour", "item", "weapon"],
  weaponTypes: ["axe", "bow", "club", "dagger", "grand-weapon", "katana", "katar", "shield", "spear", "sword", "whip"],
  armourSets: [
    "white-lion-armour",
    "screaming-armour",
    "phoenix-armour",
    "rawhide-armour",
    "leather-armour",
    "lantern-armour",
  ],
  armourLocations: ["arm-armour", "chest-armour", "head-armour", "leg-armour", "waist-armour"],
  miscellaneous: [
    "ammunition",
    "arrow",
    "balm",
    "bone",
    "consumable",
    "feather",
    "finesse",
    "flammable",
    "fragile",
    "fur",
    "heavy",
    "herb",
    "instrument",
    "jewelery",
    "lantern",
    "leather",
    "mask",
    "melee",
    "metal",
    "noisy",
    "other",
    "paired",
    "pickaxe",
    "ranged",
    "rawhide",
    "set",
    "sickle",
    "soluble",
    "stinky",
    "stone",
    "thrown",
    "tool",
    "two-handed",
  ],
};

export default categoryStructure;
