const defaultImage = new URL("../assets/gear_default.webp", import.meta.url).href;

export default {
  11: defaultImage,
  12: defaultImage,
  13: defaultImage,
  14: defaultImage,
  15: defaultImage,
  16: defaultImage,
  17: defaultImage,
  18: defaultImage,
  19: defaultImage,
  21: defaultImage,
  22: defaultImage,
  23: defaultImage,
  24: defaultImage,
  25: defaultImage,
  26: defaultImage,
  27: defaultImage,
  28: defaultImage,
  29: defaultImage,
  31: defaultImage,
  32: defaultImage,
  33: defaultImage,
  34: defaultImage,
  35: defaultImage,
  36: defaultImage,
  37: defaultImage,
  38: defaultImage,
  39: defaultImage,
  41: defaultImage,
  42: defaultImage,
  43: defaultImage,
  44: defaultImage,
  45: defaultImage,
  46: defaultImage,
  47: defaultImage,
  48: defaultImage,
  49: defaultImage,
};
